### PR TITLE
Describe the fast compilation feature

### PR DESCRIPTION
**Pull request by holyjak**

### CODE REVIEW

**Comment by KingMob** [comment]
Looks good. Question: should this functionality be exposed as a lein alias?

**Comment by holyjak** [comment]
Thank you!

You mean you want to make it possible to run `lein <something>` that would be like `lein serve` but use incremental compilation? That would be nice. How would we do that? I am not familiar with lein aliases. I guess we'd need to change https://github.com/cryogen-project/cryogen/blob/master/src/leiningen/new/cryogen/project.clj somehow ...

**Comment by KingMob** [comment]
Yeah, it's just a thought. It would be a way to expose it for using more easily than altering code.

We'd add something like:

```clojure
;; In project.clj:
:aliases {"serve-fast" ["run" "-m" "cryogen.core/a-different-main-fn-that-does-partial-compilation"]}

;; In cryogen.core:
(defn a-different-main-fn-that-does-partial-compilation
  []
  ...)
```

And then we could execute `lein serve-fast`.

Lein alias examples: https://github.com/technomancy/leiningen/blob/stable/sample.project.clj#L227-L246

**Comment by bombaywalla** [comment]
It would be best to both options (full compilation, and incremental compilation) selectable via lein and clj.

**Pull request merged**
