### PR TITLE
Migrate to latest core

### PR DESCRIPTION
**Pull request by holyjak**
Update everything so that the site works with the latest core.

### CODE REVIEW

**Comment by holyjak** [comment]
It compiles now but public/docs/ is missing

**Comment by holyjak** [comment]
All files seem to be produced now but the look of docs/home.html is different and it lacks the right menu.

**Comment by bombaywalla** [comment]
(Copied from Slack)

I just ran `lein run` and it seemed to do the right thing.
I ran `lein ring server` and that failed with an arity error.  I'm not sure it was expected to work.  But, as a result, I was not able to test the files with a web server.

I think `.circleci/config.yml` probably needs some changes too.

**Comment by holyjak** [comment]
@bombaywalla Thanks a lot for checking! Could you be so kind and look into the arity error? Because for me `lein ring server` works just fine.

And thanks for catching the CI config! I fixed that now.

**Comment by bombaywalla** [comment]
Well, I tried it again and `lein ring server` now "works" in the sense that it runs without the ArityException I was getting earlier. But, when it pops up the browser window at http://localhost:3000/index.html I get a "Page not found".  If I try http://localhost:3000/public/index.html I still get a "Page not found".

Thanks for addressing the circleci config.  I don't know much about circleci or the config, but the `resources/public` under the `store_artifacts` key could be an issue?

**Comment by bombaywalla** [comment]
I've reviewed and it looks good to go.

**Pull request merged**
